// <auto-generated />
namespace SerieList.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADDUSERSEASON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDUSERSEASON));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041632080_ADD USERSEASON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
